# constants.py

# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Paddle settings
PADDLE_WIDTH = 1
PADDLE_HEIGHT = 5
PADDLE_SPEED = 20
PADDLE_DISTANCE = 350

# Ball settings
BALL_SPEED = 10
INITIAL_MOVE_SPEED = 0.1
SPEED_INCREMENT = 0.9

# Game settings
COLLISION_DISTANCE = 50
WALL_BOUNDARY = 280
MISS_BOUNDARY = 380

# Scoreboard settings
SCORE_POSITION_Y = 200
SCORE_POSITION_X = 100